nonTerminals:
  global:
    - expression

  expression:
    - component
    - expression + component {$$ = $1 + $3;}
    - expression - component {$$ = $1 - $3;}

  factor:
    - number { $$ = (float)$1; }
    - ( expression ) { $$ = $2; }

  component:
    - factor
    - component * factor {$$ = $1 * $3;}
    - component / factor {$$ = $1 / $3;}

terminals:
  number: '/^[0-9]+/'