nonTerminals:
  E:
    - E + E { $$ = $1 + $3; }
    - E * E { $$ = $1 * $3; }
    - ( E ) { $$ = $2; }
    - NUM { $$ = $1; }

  NUM:
    - digit NUM { $$ = $1 . $2; }
    - #empty

terminals:
  digit: '/^[0-9]/'